language: python
sudo: yes

matrix:
  include:
    - env: TOXENV=py27-ansible21
    - env: TOXENV=py27-ansible20
    - env: TOXENV=py27-ansible19

install:
  - pip install tox

script:
  - tox

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

