---
# file: nodejs/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: setup.yml
  tags: installation

- name: ensure npm is installed
  apt:
    name=npm
    state=latest
  become: yes
  tags: installation
