---
# file: nodejs/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- debug: >
    msg="invoked"

- include: setup.yml
  tags: nodejs

- name: Install npm
  apt:
    name=npm
    state=latest
  become: yes
