---
# file: nodejs/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: checking installed version
  shell: "/usr/bin/test \"$(node -v 2> /dev/null)\" = v{{ nodejs_version }}"
  register: task_installed
  changed_when: false
  ignore_errors: yes

- name: setup | purge previous
  apt:
    pkg=node
    state=absent
  when: task_installed is defined and task_installed.rc == 1
  become: yes

- include: installation.yml
  when: task_installed is defined and task_installed.rc == 1
  tags: installation

- name: ensure npm is installed
  apt:
    name=npm
    state=latest
  become: yes
  tags: installation
