---
# file: nodejs/tasks/setup.yml
#
# setup.
#

- name: NodeJS | Checking installed version
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ nodejs_version }}
  register: _installed
  ignore_errors: True

- name: NodeJS | Purge previous
  apt: pkg=node state=absent
  when: _installed.rc == 1

- name: NodeJS | Fetching source
  get_url: url=http://nodejs.org/dist/v{{ nodejs_version }}/{{ nodejs_tarball }} dest={{ nodejs_tmp_path }}
  when: _installed.rc == 1

- name: NodeJS | Unpack tarball
  command: tar zxf {{ nodejs_tarball }} chdir=/tmp
  when: _installed.rc == 1

- name: NodeJS | Configure
  shell: /usr/bin/python ./configure --prefix={{ nodejs_path }} chdir={{ nodejs_tmp_path }}/{{ nodejs_prefix }}
  when: _installed.rc == 1

- name: NodeJS | Make
  shell: /usr/bin/make chdir={{ nodejs_tmp_path }}/{{ nodejs_prefix }}/
  when: _installed.rc == 1

- name: NodeJS | Make install
  shell: /usr/bin/make install chdir={{ nodejs_tmp_path }}/{{ nodejs_prefix }}/
  when: _installed.rc == 1
