- name: NodeJS | Checking installed version
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ node_version }}
  register: _installed
  ignore_errors: True

- name: NodeJS | Purge previous
  apt: pkg=node state=absent
  when: _installed.rc == 1

- name: NodeJS | Fetching source
  get_url: url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest={{ nodejs_tmp_path }}
  when: _installed.rc == 1

- name: NodeJS | Unpack tarball
  command: tar zxf {{ node_tarball }} chdir=/tmp
  when: _installed.rc == 1

- name: NodeJS | Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir={{ nodejs_tmp_path }}{{ node_prefix }}
  when: _installed.rc == 1

- name: NodeJS | Make
  shell: /usr/bin/make chdir={{ nodejs_tmp_path }}{{ node_prefix }}/
  when: _installed.rc == 1

- name: NodeJS | Make install
  shell: /usr/bin/make install chdir={{ nodejs_tmp_path }}{{ node_prefix }}/
  when: _installed.rc == 1
