---
# file: nodejs/tasks/validation.yml
#
# validation tasks.
#

- name: validation | ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - nodejs_apt_dependencies
    - nodejs_version
    - nodejs_prefix
    - nodejs_tarball
    - nodejs_path
    - nodejs_dir_src
